# Generated by Django 5.2.7 on 2025-10-23 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('idBackup', models.AutoField(primary_key=True, serialize=False)),
                ('fechaBackup', models.DateTimeField()),
                ('responsable', models.CharField(max_length=100)),
                ('tipoBackup', models.CharField(max_length=20)),
                ('resultado', models.CharField(max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaClinica',
            fields=[
                ('idCompetencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompetencia', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivelEsperado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CursoClinico',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCurso', models.CharField(max_length=100)),
                ('nivel', models.PositiveIntegerField()),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nivelDreyfus', models.CharField(max_length=20)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('fechaEvaluacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('idFuncion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFuncion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idGrupo', models.AutoField(primary_key=True, serialize=False)),
                ('codigoGrupo', models.CharField(max_length=20, unique=True)),
                ('semestre', models.CharField(max_length=10)),
                ('limiteEstudiantes', models.PositiveIntegerField(default=6)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorPrograma',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apell1', models.CharField(max_length=50)),
                ('apell2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorPractica',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apell1', models.CharField(max_length=50)),
                ('apell2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('sitioAsignado', models.CharField(max_length=100)),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idDirectorPrograma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.directorprograma')),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorCurso',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apell1', models.CharField(max_length=50)),
                ('apell2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('cursoAsignado', models.CharField(max_length=100)),
                ('semestreAsignacion', models.CharField(max_length=10)),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idCoordinadorPractica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coordinadorpractica')),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apell1', models.CharField(max_length=50)),
                ('apell2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('codigoEstudiantil', models.CharField(max_length=15, unique=True)),
                ('semestreActual', models.PositiveIntegerField()),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcion')),
                ('idGrupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEvaluacion',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCambio', models.DateTimeField()),
                ('usuarioEditor', models.CharField(max_length=100)),
                ('detalleCambio', models.TextField()),
                ('idEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.evaluaciondocente')),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('idPractica', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('cedulaCoordinadorPractica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coordinadorpractica')),
                ('cedulaEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estudiante')),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cursoclinico')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoClinico',
            fields=[
                ('idProcedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProcedimiento', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('simulado', models.BooleanField(default=False)),
                ('idCompetencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.competenciaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoRealizado',
            fields=[
                ('idProcedimientoRealizado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('resultadoEvaluacionProfesor', models.CharField(max_length=20)),
                ('resultadoAutoevaluacionEstudiante', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('idPractica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.practica')),
                ('idProcedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedimientoclinico')),
            ],
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='idProcedimientoRealizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedimientorealizado'),
        ),
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('idAutoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nivelPercibido', models.CharField(max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fechaAutoevaluacion', models.DateField()),
                ('cedulaEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estudiante')),
                ('idProcedimientoRealizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedimientorealizado')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apell1', models.CharField(max_length=50)),
                ('apell2', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('cursoAsignado', models.CharField(max_length=100)),
                ('semestreAsignacion', models.CharField(max_length=10)),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idCoordinadorCurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coordinadorcurso')),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcion')),
            ],
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='cedulaProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipoReporte', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=20)),
                ('fechaGeneracion', models.DateField()),
                ('contenido', models.TextField()),
                ('cedulaEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('idRetroalimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateField()),
                ('cedulaProfesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesor')),
                ('idEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retroalimentaciones', to='core.evaluaciondocente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasenaHash', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=15)),
                ('ultimoAcceso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraSistema',
            fields=[
                ('idLog', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('detalle', models.TextField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
    ]
