# Generated by Django 5.2.7 on 2025-10-24 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, help_text='Calificación numérica de 0.0 a 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
