# Generated by Django 5.2.7 on 2025-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evaluaciondocente_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluacion',
            name='nivelPercibido',
            field=models.CharField(choices=[('NOVATO', 'Novato'), ('PRINCIPIANTE_AVANZADO', 'Principiante Avanzado'), ('COMPETENTE', 'Competente'), ('PROFESIONAL', 'Profesional'), ('EXPERTO', 'Experto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='competenciaclinica',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competenciaclinica',
            name='nivelEsperado',
            field=models.CharField(choices=[('NOVATO', 'Novato'), ('PRINCIPIANTE_AVANZADO', 'Principiante Avanzado'), ('COMPETENTE', 'Competente'), ('PROFESIONAL', 'Profesional'), ('EXPERTO', 'Experto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='nivelDreyfus',
            field=models.CharField(choices=[('NOVATO', 'Novato'), ('PRINCIPIANTE_AVANZADO', 'Principiante Avanzado'), ('COMPETENTE', 'Competente'), ('PROFESIONAL', 'Profesional'), ('EXPERTO', 'Experto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='procedimientorealizado',
            name='resultadoAutoevaluacionEstudiante',
            field=models.CharField(choices=[('NOVATO', 'Novato'), ('PRINCIPIANTE_AVANZADO', 'Principiante Avanzado'), ('COMPETENTE', 'Competente'), ('PROFESIONAL', 'Profesional'), ('EXPERTO', 'Experto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='procedimientorealizado',
            name='resultadoEvaluacionProfesor',
            field=models.CharField(choices=[('NOVATO', 'Novato'), ('PRINCIPIANTE_AVANZADO', 'Principiante Avanzado'), ('COMPETENTE', 'Competente'), ('PROFESIONAL', 'Profesional'), ('EXPERTO', 'Experto')], max_length=50),
        ),
    ]
