# Generated by Django 5.2.7 on 2025-10-24 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autoevaluacion_nivelpercibido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoclinico',
            name='periodoAcademico',
            field=models.CharField(default=2025, help_text='Formato: YYYY-1 o YYYY-2 (Ejemplo: 2025-1, 2025-2)', max_length=6, validators=[django.core.validators.RegexValidator(message='El periodo académico debe tener el formato YYYY-1 o YYYY-2.', regex='^\\d{4}-[1-2]$')]),
            preserve_default=False,
        ),
    ]
