# Generated by Django 5.2.7 on 2025-10-24 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cursoclinico_periodoacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='cedulaProfesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='core.profesor'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='idCurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.cursoclinico'),
            preserve_default=False,
        ),
    ]
