# Generated by Django 5.2.7 on 2025-10-24 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grupo_cedulaprofesor_grupo_idcurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retroalimentacion',
            old_name='texto',
            new_name='comentarios',
        ),
        migrations.AlterField(
            model_name='autoevaluacion',
            name='comentarios',
            field=models.TextField(default='Pendiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competenciaclinica',
            name='descripcion',
            field=models.TextField(default='Pendiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigoEstudiantil',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe contener solo números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='semestreActual',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='retroalimentacion',
            field=models.TextField(default='Pendiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='codigoGrupo',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe contener solo números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='semestre',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
        migrations.AlterField(
            model_name='procedimientoclinico',
            name='tipo',
            field=models.CharField(choices=[('DIAGNOSTICO', 'Diagnostico'), ('TERAPEUTICO', 'Terapéutico'), ('PREVENTIVO', 'Preventivo'), ('REHABILITACION', 'Rehabilitación')], max_length=50),
        ),
        migrations.AlterField(
            model_name='procedimientorealizado',
            name='observaciones',
            field=models.TextField(default='Pendiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimientorealizado',
            name='tipo',
            field=models.CharField(choices=[('REAL', 'Real'), ('SIMULADO', 'Simulado')], max_length=20),
        ),
    ]
