# Generated by Django 5.2.7 on 2025-10-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_texto_retroalimentacion_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='limiteEstudiantes',
        ),
    ]
