# Generated by Django 5.2.7 on 2025-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_grupo_limiteestudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoclinico',
            name='nivel',
        ),
        migrations.AddField(
            model_name='cursoclinico',
            name='semestre',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
    ]
