# Generated by Django 5.2.7 on 2025-10-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cursoclinico_nivel_cursoclinico_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluacion',
            name='cedulaEstudiante',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='autoevaluacion',
            name='idProcedimientoRealizado',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='core.procedimientorealizado'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='tipoBackup',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('INCREMENTAL', 'Incremental'), ('DIFERENCIAL', 'Diferencial')], max_length=20),
        ),
    ]
