# Generated by Django 5.2.7 on 2025-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_autoevaluacion_cedulaestudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoclinico',
            name='codigoCurso',
            field=models.CharField(default='CL000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
