# Generated by Django 5.2.7 on 2025-10-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cursoclinico_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='semestre',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
    ]
