# Generated by Django 5.2.7 on 2025-10-29 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_grupo_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codigoGrupo',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe contener solo números.', regex='^[A-Za-z0-9\\s\\-]+$')]),
        ),
    ]
