# Generated by Django 5.2.7 on 2025-10-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluacion',
            name='comoSeSintio',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cómo se sintió?'),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='principalesAprendizajes',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuáles fueron tus principales aprendizajes de esta sesión?'),
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='comoSeSintio',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cómo se sintió el estudiante durante la sesión?'),
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='principalesAprendizajes',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuáles fueron los principales aprendizajes observados?'),
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='retroalimentacionProfesor',
            field=models.TextField(blank=True, null=True, verbose_name='Retroalimentación cualitativa del profesor'),
        ),
    ]
