# Generated by Django 5.2.7 on 2025-11-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notificacion_tipo_alter_estudiante_apell1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apell1',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre1',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono1',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
    ]
