# Generated by Django 5.2.7 on 2025-11-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_estudiante_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluacion',
            name='cedulaEstudiante',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='autoevaluacion',
            name='idProcedimientoRealizado',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.procedimientorealizado'),
        ),
    ]
